import type { Metadata } from 'next'
import Link from 'next/link'
import { DocHeader, Section, Prose, Callout, Card, Facts, NextSteps } from '@/components/developers/doc'
import { CodeBlock } from '@/components/shared/code-block'
import { readExample } from '@/lib/examples'
import { MAILTO, RECORDED } from '@/content/developers/meta'
import results from '../../../../manual/data/api-results.json'

export const metadata: Metadata = {
  title: 'Quick start: your first CPET analysis over the API',
  description:
    'From no key to a first cardiopulmonary exercise test analysis: fetch synthetic CPET data, upload it to the Oxynet API with curl or Python, and read ventilatory thresholds with their provenance.',
  alternates: { canonical: '/developers/quickstart' },
}

const NO_KEY = `# No key needed: the synthetic sample and the schema are public
curl -s https://app.oxynet.net/v1/sample | jq '{filename, note, expected}'
curl -s https://app.oxynet.net/v1/openapi.json | jq '.paths | keys'`

const SAMPLE_TO_ANALYSIS = `export OXYNET_API_KEY=sk_live_...   # keep it out of files and logs

# Fetch the synthetic sample and upload it in one pipe
ID=$(curl -s https://app.oxynet.net/v1/sample \\
  | jq '{filename, content}' \\
  | curl -s -H "X-API-Key: $OXYNET_API_KEY" -H 'Content-Type: application/json' \\
      -d @- https://app.oxynet.net/v1/cpet/content \\
  | jq -r .cpet_id)

curl -s -H "X-API-Key: $OXYNET_API_KEY" -H 'Content-Type: application/json' \\
  -d '{"analyses": ["vt"]}' \\
  https://app.oxynet.net/v1/cpet/$ID/analyze | jq '.results[0]'`

const BUILD = [
  {
    who: 'Clinical application',
    how: 'Store the envelope beside the test. Show findings, print notes verbatim in the report, keep provenance for audit.',
  },
  {
    who: 'Research software',
    how: 'One row per recording: findings as columns, analysis_version and model_version as columns too, so a re-run on a new version is a visible difference and not a silent one.',
  },
  {
    who: 'Report generator',
    how: 'Template the numbers; never template away the notes. A refused analysis becomes a sentence saying why, not an empty cell.',
  },
  {
    who: 'AI agent',
    how: 'Connect over MCP. The agent reasons over the structured results; the thresholds come from the model, not from the agent reading a trace.',
  },
  {
    who: 'Exercise physiology workflow',
    how: 'Thresholds in time and in V̇O₂, substrate use against %V̇O₂peak (or watts when a load channel exists), for prescription tools downstream.',
  },
]

export default function QuickStartPage() {
  const py = readExample('examples/python/quickstart.py')
  const sh = readExample('examples/rest/quickstart.sh')
  const vt = results.vt

  return (
    <>
      <DocHeader
        eyebrow="Quick start"
        title="From no key to a first analysis"
        lede={<p>Five steps. The first two need no account, and none of them needs patient data.</p>}
      />

      <Section id="access" title="1. Get access">
        <Prose>
          <p>
            Every call except the public ones below needs an API key in the{' '}
            <code>X-API-Key</code> header. Keys are issued by Oxynet on request; there is no
            self-service signup yet. A key starts with <code>sk_live_</code> and grants specific
            analyses (thresholds, oscillation and substrate are licensed separately), so the first
            call with it should be <code>GET /v1/capabilities</code>.
          </p>
        </Prose>
        <div className="flex flex-wrap gap-3 my-6">
          <a href={MAILTO.key} className="inline-flex items-center gap-1.5 text-sm font-medium bg-accent-fill text-black rounded-lg px-4 py-2 hover:bg-accent/85 transition-colors">
            Request an API key
          </a>
          <Link href="/developers/api/v1#auth" className="inline-flex items-center text-sm font-medium border border-hairline rounded-lg px-4 py-2 hover:border-accent/40 transition-colors text-ink-strong">
            How authentication works
          </Link>
        </div>
        <Prose className="mb-4"><p>While you wait, this much works without one:</p></Prose>
        <CodeBlock code={NO_KEY} lang="sh" copy />
        <Callout tone="todo" title="Not yet available" className="mt-6">
          <p>
            A self-service sandbox key. Until one exists, a request with a sentence on what you
            want to build is enough to receive a trial key.
          </p>
        </Callout>
      </Section>

      <Section id="sample" title="2. Get sample data">
        <Prose>
          <p>
            Use the synthetic recording before anything of yours. It is generated by the API (
            <code>GET /v1/sample</code>), 900 seconds of an incremental test at 2 s intervals, with
            V&#775;O&#8322;, V&#775;CO&#8322;, V&#775;E, breathing frequency, end-tidal gases and heart
            rate. It is not a person and it is not validation data: the thresholds sit near 55 % and
            80 % of the test because the generator placed them there.
          </p>
          <p>
            Fetch it live, as in step 3, or <Link href="/developers/downloads#samples">download the saved copies</Link>,
            including one with an oscillation for the research analysis.
          </p>
        </Prose>
      </Section>

      <Section id="run" title="3. Run Oxynet">
        <Prose className="mb-5"><p>The shortest route, sample to thresholds with curl and jq:</p></Prose>
        <CodeBlock code={SAMPLE_TO_ANALYSIS} lang="sh" copy />
        <Prose className="my-6">
          <p>
            The complete flow on a file from disk (capabilities, upload, analyses, derived
            quantities, deletion), in the two forms it is downloadable in:
          </p>
        </Prose>
        <div className="space-y-6">
          <CodeBlock code={py.code} lang="python" filename="python/quickstart.py" download={py.href} copy />
          <CodeBlock code={sh.code} lang="bash" filename="rest/quickstart.sh" download={sh.href} copy />
        </div>
        <Callout className="mt-6">
          <p>
            Your own files go in the same way: the vendor export, unchanged. Remove names and dates of
            birth from the file and the filename first; Oxynet needs no identifiers. For a file on
            disk reached through an agent, use an upload ticket (<code>POST /v1/uploads</code>) so
            the bytes never pass through the conversation.
          </p>
        </Callout>
      </Section>

      <Section id="inspect" title="4. Inspect the result">
        <Prose className="mb-5">
          <p>
            <code>analyze</code> returns <code>{'{cpet_id, results: [...]}'}</code>, one envelope
            per analysis, all the same shape. This is the threshold envelope as recorded from the
            live API on {RECORDED.taken} for the manual&apos;s reference recording (a de-identified
            real test, not the synthetic sample):
          </p>
        </Prose>
        <CodeBlock code={JSON.stringify(vt, null, 2)} lang="json" filename={`analyze → results[0]  ·  analysis_version ${RECORDED.analysisVersion}`} copy />
        <Prose className="mt-3 mb-6">
          <p className="text-xs text-ink-faint">
            As stored for the manual, which kept only these fields. A live response also carries{' '}
            <code>analysis</code>, <code>notes</code>, and <code>schema_version</code> and{' '}
            <code>computed_at</code> in provenance.
          </p>
        </Prose>
        <Facts
          rows={[
            [<code key="s">status</code>, <>&quot;ok&quot;, or &quot;not_analysable&quot; with an error code and the reason. Other analyses in the same call still run.</>],
            [<code key="f">findings</code>, 'VT1 and VT2 in seconds from the start and in mL/min of oxygen uptake.'],
            [<code key="q">quality</code>, 'good, acceptable or poor: how complete the RECORDING is. Not a confidence in the thresholds.'],
            [<code key="n">notes</code>, 'Caveats that belong in any report built on these numbers.'],
            [<code key="p">provenance</code>, 'Which model and version ran, the analysis version, when, and how long it took.'],
          ]}
        />
        <p className="mt-4 text-sm">
          <Link href="/developers/outputs" className="text-accent hover:underline">Every field, and the other two analyses →</Link>
        </p>
      </Section>

      <Section id="build" title="5. Build">
        <div className="grid sm:grid-cols-2 gap-4">
          {BUILD.map((b) => (
            <Card key={b.who}>
              <h3 className="text-sm font-semibold text-ink-strong mb-2">{b.who}</h3>
              <p className="text-sm text-ink-body leading-relaxed">{b.how}</p>
            </Card>
          ))}
        </div>
      </Section>

      <NextSteps
        links={[
          { href: '/developers/api/v1', label: 'API reference (v1)', note: 'Every endpoint, error and limit.' },
          { href: '/developers/partners', label: 'Integrating a product?', note: 'What happens after the first successful call.' },
        ]}
      />
    </>
  )
}
